import { Roboto } from 'next/font/google';
import { getCssText } from '@/styles/index';
import { globalStyles } from '@/styles/global';
import { Header, Container } from '@/styles/app/app';
import logoImg from '../assets/logo.svg'

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) { 
  return (
    <html lang="pt-br">
      <head>
        <style id="stitches" dangerouslySetInnerHTML={{__html: `${getCssText()}${globalStyles()}`}} />
      </head>
      <body className={roboto.className}>
        <Container>

            <Header>
              <img src={logoImg.src} alt="" />
            </Header>
            {children}  

        </Container>
      </body>
    </html>
  )
}
